services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dev_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network


  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"  
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  ts-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env.dev
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: npx tsx src/main/server.ts
    networks:
      - app-network

volumes:
  pgdata_dev:

networks:
  app-network:
    driver: bridge