"""
Structured Logger implementation using Structlog & Logging module.
Supports environment-based dynamic output routing, custom logging levels,
stream redirection, and safe Singleton implementation.
"""

from __future__ import annotations

import logging
from logging.handlers import RotatingFileHandler
import os
from pathlib import Path
import sys
from typing import Any

import structlog


from src.main.config import config


class AppLogger:
    """
    Singleton Wrapper for Application Logging Configuration.
    Ensures a single initialization step across the composition root.
    """

    _instance: AppLogger | None = None
    _initialized: bool = False

    def __new__(cls) -> AppLogger:
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    def __init__(self) -> None:
        if self._initialized:
            return

        self._configure_logger()
        self._override_standard_outputs()
        AppLogger._initialized = True

    def _configure_logger(self) -> None:
        """Configures logger handlers, formatting, levels, and fallback logic."""

        # 1. d. Determine Logging Level based on ENV
        log_level = logging.DEBUG if config.env == "dev" else logging.INFO

        handlers: list[logging.Handler] = []

        # 1. Address output stream based on ENV
        if config.env == "dev":
            # Output to Console (business as usual)
            console_handler = logging.StreamHandler(sys.stdout)
            console_handler.setLevel(log_level)
            handlers.append(console_handler)
            renderer = structlog.dev.ConsoleRenderer(colors=True)
        else:
            # Output to Log File in Production
            # 1. c. Handle initialization gracefully & handle errors
            try:
                log_dir = Path("logs")
                log_dir.mkdir(parents=True, exist_ok=True)
                file_path = log_dir / "app.log"

                # Standard Rotating File Handler (Max 10MB per file, max 5 backups)
                file_handler = RotatingFileHandler(
                    file_path, maxBytes=10_000_000, backupCount=5, encoding="utf-8"
                )
                file_handler.setLevel(log_level)
                handlers.append(file_handler)
            except (PermissionError, OSError) as e:
                # Fallback to Console if file system is unwritable
                print(f" WARNING: Failed to initialize file logger ({e}). Falling back to stdout.", file=sys.stderr)
                fallback_handler = logging.StreamHandler(sys.stderr)
                fallback_handler.setLevel(log_level)
                handlers.append(fallback_handler)

            # 1. a. Structured JSON format for long-term production analytics
            renderer = structlog.processors.JSONRenderer()

        # Root logger setup
        root_logger = logging.getLogger()
        root_logger.setLevel(log_level)
        root_logger.handlers = handlers

        # Structlog pipelines
        structlog.configure(
            processors=[
                structlog.contextvars.merge_contextvars,
                structlog.stdlib.add_log_level,
                structlog.processors.StackInfoRenderer(),
                structlog.processors.TimeStamper(fmt="iso"),
                structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
            ],
            logger_factory=structlog.stdlib.LoggerFactory(),
            wrapper_class=structlog.stdlib.BoundLogger,
            cache_logger_on_first_use=True,
        )

        # Standard Library Formatter Integration
        formatter = structlog.stdlib.ProcessorFormatter(
            foreign_pre_chain=[
                structlog.stdlib.add_log_level,
                structlog.processors.TimeStamper(fmt="iso"),
            ],
            processor=renderer,
        )

        for handler in root_logger.handlers:
            handler.setFormatter(formatter)

    def _override_standard_outputs(self) -> None:
        """
        2. Overwrite standard print/sys.stdout execution so that built-in
        print() statements get processed by structlog instead of raw printing.
        """

        class PrintToLogger:
            def __init__(self, level_func: Any) -> None:
                self.level_func = level_func

            def write(self, message: str) -> None:
                cleaned = message.strip()
                if cleaned:  # Ignore empty lines generated by print()
                    self.level_func(cleaned, source="redirected_print")

            def flush(self) -> None:
                pass

        # Redirect standard stdout print calls to structlog info level
        sys.stdout = PrintToLogger(logger.info)  # type: ignore[assignment]


# 3. Singleton instance creation
_logger_instance = AppLogger()
logger = structlog.get_logger()